server:
  port: 5566

#MYSQL
#spring:
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/sparrow-frame?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
#    password: 12345678

my:
  name: "ChenDi"
